/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.scene.control.Label;
//import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class Main extends Application {
	
	@Override
	public void start(Stage stage) throws IOException {
		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(Main.class.getResource("FXMLS.fxml"));
		Pane ventana = (Pane) loader.load();
		
		Scene scene = new Scene(ventana);
		stage.setScene(scene);
		stage.show();
	}
	
	public static void main(String[] args) {
		launch(args);
	}
	
//	@Override
//  public void start(Stage stage) throws IOException {
//		Parent root = FXMLLoader.load(getClass().getResource("FXMLCalc.fxml"));
//		Scene scene = new Scene(root);
//		stage.setScene(scene);
//		stage.show();
//		
//	}
//	
//	public static void main(String[] args) {
//		launch(args);
//	}
	

//    @Override
//    public void start(Stage stage) {
//        String javaVersion = System.getProperty("java.version");
//        String javafxVersion = System.getProperty("javafx.version");
//        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
//        Scene scene = new Scene(new StackPane(l), 640, 480);
//        stage.setScene(scene);
//        stage.show();
//    }

//	@Override
//	public void start(Stage stage) throws Exception {
//		Parent root = FXMLLoader.load(getClass().getResource("BasicFXML.fxml"));
//		Scene scene = new Scene(root);
//		stage.setScene(scene);
//		stage.show();
//	}
//
//	public static void main(String[] args) {
//		launch();
//	}
}
